@file:Suppress("RemoveRedundantQualifierName")

package me.melijn.melijnbot.internals.command

import me.melijn.melijnbot.Container
import me.melijn.melijnbot.commands.administration.*
import me.melijn.melijnbot.commands.animal.*
import me.melijn.melijnbot.commands.anime.*
import me.melijn.melijnbot.commands.developer.*
import me.melijn.melijnbot.commands.economy.*
import me.melijn.melijnbot.commands.games.PokerCommand
import me.melijn.melijnbot.commands.games.RockPaperScissorsCommand
import me.melijn.melijnbot.commands.games.SlotsCommand
import me.melijn.melijnbot.commands.games.TicTacToeCommand
import me.melijn.melijnbot.commands.image.*
import me.melijn.melijnbot.commands.moderation.*
import me.melijn.melijnbot.commands.nsfw.*
import me.melijn.melijnbot.commands.utility.*
import me.melijn.melijnbot.internals.threading.TaskManager
import org.slf4j.LoggerFactory

class CommandClientBuilder(private val container: Container) {

    private val logger = LoggerFactory.getLogger(this::class.java.name)

    init {
        logger.info("Loading commands...")
    }

    private val commands = hashSetOf(
        PunishmentCommand(),
        SetCommandStateCommand(),
        PunchCommand(),
        ColorCommand(),
        KickCommand(),
        SetLogChannelCommand(),
        KissCommand(),
        MirrorCommand(),
        LickCommand(),
        NyancatCommand(),
        ForceRoleCommand(),
        TestCommand(),
        BiteCommand(),
        SetChannelCommand(),
        GreyScaleCommand(),
        InfoCommand(),
        GifInfoCommand(),
        FilterCommand(),
        TempBanCommand(),
        DabCommand(),
        HelpCommand(),
        PrefixesCommand(),
        MuteCommand(),
        StatsCommand(),
        CatCommand(),
        KoalaCommand(),
        SoftBanCommand(),
        RawCommand(),
        BirdCommand(),
        AvatarCommand(),
        SetCooldownCommand(),
        MetricsCommand(),
        UnmuteCommand(),
        PurgeCommand(),
        VoteCommand(),
        SetVerificationTypeCommand(),
        FilterGroupCommand(),
        BlushCommand(),
        StareCommand(),
        TempMuteCommand(),
        VerifyCommand(),
        SetSlowModeCommand(),
        GreetCommand(),
        BanCommand(),
        InvertCommand(),
//        RestartCommand(),
        UrbanCommand(),
        HistoryCommand(),
        RoleInfoCommand(),
        AwooCommand(),
        AlpacaCommand(),
        PermissionCommand(),
        WarnCommand(),
        T2eCommand(),
        FlipImgCommand(),
        ClearChannelCommand(),
        ServerInfoCommand(),
        PatCommand(),
        SelfRoleCommand(),
        PingCommand(),
        HighfiveCommand(),
        InviteCommand(),
        BlurCommand(),
        SetEmbedColorCommand(),
        PandaCommand(),
        CuddleCommand(),
        SlapCommand(),
        EmoteCommand(),
        OldBlurpleCommand(),
        SetMaxUserVerificationFlowRateCommand(),
        UnicodeCommand(),
        UnbanCommand(),
        SpookifyCommand(),
        HugCommand(),
        SetPrivateEmbedColorCommand(),
        RolesCommand(),
        VoteInfoCommand(),
        FoxCommand(),
        PixelateCommand(),
        TickleCommand(),
        SharpenCommand(),
        ThinkingCommand(),
        HandholdingCommand(),
        ShardsCommand(),
        SayCommand(),
        ShootCommand(),
        SettingsCommand(),
        PokeCommand(),
        PrivatePrefixesCommand(),
        MeguminCommand(),
        SetEmbedStateCommand(),
        LewdCommand(),
        ShrugCommand(),
        PunishmentGroupCommand(),
        PoutCommand(),
        EvalCommand(),
        OwOCommand(),
        SmugCommand(),
        SetVerificationPasswordCommand(),
        DonateCommand(),
        CryCommand(),
        DiscordMemeCommand(),
        SetRoleCommand(),
        UserInfoCommand(),
        SetLanguageCommand(),
        SetVerificationEmotejiCommand(),
        DogCommand(),
        CustomCommandCommand(),
        ThumbsupCommand(),
        NekoCommand(),
        SetPrivateLanguageCommand(),
        SetBirthdayCommand(),
        SetPrivateTimeZoneCommand(),
        SetTimeZoneCommand(),
        SpamCommand(),
        DuckCommand(),
        AIWaifuCommand(),
        SupportCommand(),
        GifCommand(),
        AppendReverseGifCommand(),
        GlobalRecolorCommand(),
        JoinRoleCommand(),
        MassMoveCommand(),
        LimitRoleToChannelCommand(),
        SetBannedOrKickedTriggersLeaveCommand(),
        SetBotLogStateCommand(),
        SetRoleColorCommand(),
        AniListCommand(),
        NekoHCommand(),
        Rule34Command(),
        SafebooruCommand(),
        TBibCommand(),
        GelbooruCommand(),
        PngsFromGifCommand(),
        PngsToGifCommand(),
        ReplaceColorCommand(),
        SetAllowSpacedPrefixState(),
        SetPrivateAllowSpacedPrefixState(),
        AliasesCommand(),
        PrivateAliasesCommand(),
        ManageHistoryCommand(),
        PenguinCommand(),
        PossumCommand(),
        BalanceCommand(),
        SetBalanceCommand(),
        SetRemoveResponsesCommand(),
        SetRemoveInvokeCommand(),
        ManageSupportersCommand(),
        me.melijn.melijnbot.commands.economy.FlipCommand(),
        DailyCommand(),
        PayCommand(),
        LeaderBoardCommand(),
        TopVotersCommand(),
        ToggleVoteReminderCommand(),
        MikuCommand(),
        RedisCommand(),
        RedditCommand(),
        MemeCommand(),
        BonkCommand(),
        OsuCommand(),
        EmotesCommand(),
        IDInfoCommand(),
        IAmCommand(),
        IAmNotCommand(),
        TokenInfoCommand(),
        ChannelInfoCommand(),
        ReverseImageSearchCommand(),
        GoogleReverseImageSearch(),
        BoostersCommand(),
        ClearCacheCommand(),
        SlotsCommand(),
        PokerCommand(),
        JailCommand(),
        // CalculateCommand(),
        SnipeCommand(),
        SnekCommand(),
        StarboardCommand(),
        RemindmeCommand(),
        ShipCommand(),
        TicTacToeCommand(),
        RockPaperScissorsCommand(),
        RepCommand(),
        BegCommand(),
        ChickenCommand(),
        FishCommand(),
        LockCommand(),
        UnlockCommand(),
        FlipXCommand(),
        TimeCommand(),
        NomCommand(),
        ConfusedCommand(),
        FrogCommand(),
        ChangeNameCommand(),
        ScriptsCommand(),
        LynxCommand(),
        SyncChannelCommand(),
        MoveChannelCommand(),
        SetChannelCategory(),
        SetAutoRemoveInactiveJoinMessagesDuration(),
        MessageCommand(),
        LinkMessageCommand(),
        ChannelRoleCommand(),
        GiveRoleCommand(),
        TakeRoleCommand(),
        ToggleRoleCommand(),
        MassBanCommand(),
        MassUnbanCommand(),
        MassKickCommand(),
        BlurpleCommand(),
        BotBanCommand(),
        VintageCommand(),
        SpeedupGifCommand(),
        BrightnessCommand(),
        JPGCommand(),
        PNGCommand(),
        WebpCommand(),
        RotateRightCommand(),
        RotateLeftCommand(),
        TrimCommand(),
        TakeCommand(),
        ContrastCommand(),
        KaleidoScopeCommand(),
        CalculateCommand(),
        ChannelFlagsCommand(),
        DiceCommand(),
        ManiaCommand(),
        TaikoCommand(),
        CatchTheBeatCommand(),
        YoshiCommand(),
        CloneRolePermissionsCommand(),
        SetChannelOverrideCommand(),
        OenkCommand(),
    )

    fun build(): CommandClient {
        return CommandClient(commands.toSet(), container)
    }

    fun loadCommands(): CommandClientBuilder {
        TaskManager.async {
            container.daoManager.commandWrapper.bulkInsert(commands)
        }
        logger.info("Loaded ${commands.size} commands")
        return this
    }
}