package me.melijn.jda.blub;

public enum ChannelType {
    BAN_LOG, WARN_LOG, MUTE_LOG, KICK_LOG, SDM_LOG, ODM_LOG, PM_LOG, FM_LOG, MUSIC_LOG, MUSIC, WELCOME, VERIFICATION, SELF_ROLE, EM_LOG, REACTION_LOG, ATTACHMENT_LOG
}
